### ISSUE TITLE
正規表現には対応していますでしょうか？

### ISSUE THREAD

**Issue by userUseruseR01** [swen128/youtube-live-chat-filter#1]
正規表現にてNG設定を行いたいと考えています
可能でしょうか？

^.$ 一文字投稿や
(..+)\1{3,} 連続した書込みをブロックしたいです。。。

**Comment by swen128** [comment]
ご意見ありがとうございます
正規表現に対応した新バージョンの 0.2.0 をリリースしました

オプションで「正規表現でフィルターする」をオンにして、
テキストボックスの一行ごとに正規表現で NG パターンを記述してください

**Comment by userUseruseR01** [comment]
ありがとうございます！！
