### ISSUE TITLE
特定ユーザーメッセージのメニューを対応するユーザーが間違ってる

### ISSUE THREAD

**Issue by JohnsonChung** [swen128/youtube-live-chat-filter#3]
例：
機能作動中に（NGワード設定済）
このメニューは見た目にそのユーザーの直ぐ側にありますが、
封鎖を押すと下の別のユーザーが封鎖されてしまいます。
![image](https://user-images.githubusercontent.com/4928770/69015520-aaffea00-09cf-11ea-8dea-eb330ec8d975.png)

**Comment by swen128** [comment]
ご報告ありがとうございます。

こちらのバグを修正した最新版をリリースしました。
